
package Forms;

import Clases.DataBase;
import Clases.Decoration;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

public class LoginForm extends javax.swing.JFrame {

   
    Clases.Decoration decoration = new Decoration();
    
    public LoginForm() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        decoration.displayImage(jLabel_image.getWidth(), jLabel_image.getHeight(), "/Images/login_image.jpg", jLabel_image);
        
        Border userBorder = BorderFactory.createMatteBorder(0, 0, 3, 0, new Color(36, 37, 42));
        jTextField_username.setBorder(userBorder);
        
        Border pwBorder = BorderFactory.createMatteBorder(0, 0, 3, 0, new Color(36, 37, 42));
        jPasswordField.setBorder(pwBorder);
        
        Border btnBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(34,49,63));
        jButton_login.setBorder(btnBorder);
        
        emptyError.setVisible(false);
        invalidError.setVisible(false);
        adminError.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_background = new javax.swing.JPanel();
        jPanel_image = new javax.swing.JPanel();
        jLabel_image = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_ut = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton_login = new javax.swing.JButton();
        emptyError = new javax.swing.JLabel();
        invalidError = new javax.swing.JLabel();
        adminError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_background.setBackground(new java.awt.Color(255, 255, 255));

        jPanel_image.setBackground(new java.awt.Color(255, 204, 204));
        jPanel_image.setPreferredSize(new java.awt.Dimension(385, 480));

        javax.swing.GroupLayout jPanel_imageLayout = new javax.swing.GroupLayout(jPanel_image);
        jPanel_image.setLayout(jPanel_imageLayout);
        jPanel_imageLayout.setHorizontalGroup(
            jPanel_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_image, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
        );
        jPanel_imageLayout.setVerticalGroup(
            jPanel_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_image, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(34, 49, 63));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(56, 79, 95));
        jLabel1.setText("LAHIRU FURNITURES");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(56, 79, 95));
        jLabel2.setText("Username");

        jTextField_username.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jTextField_username.setForeground(new java.awt.Color(36, 37, 42));
        jTextField_username.setBorder(null);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(56, 79, 95));
        jLabel3.setText("Password");

        jPasswordField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jPasswordField.setForeground(new java.awt.Color(36, 37, 42));
        jPasswordField.setBorder(null);
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(56, 79, 95));
        jLabel4.setText("User Type");

        jComboBox_ut.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jComboBox_ut.setForeground(new java.awt.Color(36, 37, 42));
        jComboBox_ut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "SalesPerson" }));
        jComboBox_ut.setBorder(null);

        jCheckBox1.setForeground(new java.awt.Color(56, 79, 95));
        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jButton_login.setBackground(new java.awt.Color(255, 255, 255));
        jButton_login.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jButton_login.setForeground(new java.awt.Color(34, 49, 63));
        jButton_login.setText("Login >>");
        jButton_login.setBorder(null);
        jButton_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });

        emptyError.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        emptyError.setForeground(new java.awt.Color(255, 0, 0));
        emptyError.setText("*Enter username and password");
        emptyError.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emptyErrorMouseClicked(evt);
            }
        });

        invalidError.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        invalidError.setForeground(new java.awt.Color(255, 0, 0));
        invalidError.setText("*Invalid username or password");
        invalidError.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invalidErrorMouseClicked(evt);
            }
        });

        adminError.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        adminError.setForeground(new java.awt.Color(255, 0, 0));
        adminError.setText("*Sorry! You are not an Admin");
        adminError.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminErrorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_backgroundLayout = new javax.swing.GroupLayout(jPanel_background);
        jPanel_background.setLayout(jPanel_backgroundLayout);
        jPanel_backgroundLayout.setHorizontalGroup(
            jPanel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_backgroundLayout.createSequentialGroup()
                .addComponent(jPanel_image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_username)
                            .addComponent(jLabel3)
                            .addComponent(jPasswordField)
                            .addComponent(emptyError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(invalidError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jCheckBox1))
                    .addComponent(jButton_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_ut, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(adminError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel_backgroundLayout.setVerticalGroup(
            jPanel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_backgroundLayout.createSequentialGroup()
                .addComponent(jPanel_image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel_backgroundLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emptyError)
                .addGap(3, 3, 3)
                .addComponent(invalidError)
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox_ut, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminError)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected())
        {
            jPasswordField.setEchoChar((char)0);
        }
        else
        {
            jPasswordField.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    public static String name;
    public static int userID;
    
    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed

        String username = jTextField_username.getText();
        String password = String.valueOf(jPasswordField.getPassword());

        PreparedStatement pst;
        PreparedStatement pst2;
        ResultSet rs;
        ResultSet rs2;

        String query = "SELECT * FROM `login` WHERE `username` = ? AND `password` = ?";
        String query2 = "SELECT `role`, `f_name`, `l_name` FROM `users` WHERE `user_id` = ?";

        if(username.trim().equals("") || password.trim().equals(""))
        {
            emptyError.setVisible(true);
        }
        else
        {
            try {

                pst = DataBase.getConnection().prepareStatement(query);
                pst.setString(1, username);
                pst.setString(2, password);

                rs = pst.executeQuery();

                if(rs.next())
                {

                    int userId = rs.getInt("user_id");
                    LoginForm.userID = userId;

                    pst2 = DataBase.getConnection().prepareStatement(query2);
                    pst2.setInt(1, userId);

                    rs2 = pst2.executeQuery();

                    String userType = (String) jComboBox_ut.getSelectedItem();

                    if("Admin".equals(userType))
                    {
                        if(rs2.next())
                        {
                            String role = rs2.getString("role");
                            String fname = rs2.getString("f_name");
                            String lname = rs2.getString("l_name");
                            if(userType.equals(role)){
                                LoginForm.name = fname+" "+lname;
                                DashboardForm2 dashboard = new DashboardForm2();
                                dashboard.setVisible(true);
                                this.dispose();
                            }
                            else
                            {
                                adminError.setVisible(true);
                            }
                        }
                    }
                    else if("SalesPerson".equals(userType))
                    {
                        if(rs2.next())
                        {
                            String fname = rs2.getString("f_name");
                            String lname = rs2.getString("l_name");
                            LoginForm.name = fname+" "+lname;
                            HomeForm2 home = new HomeForm2();
                            home.setVisible(true);
                            this.dispose();
                            
                        }
                        
                    }

                }
                else
                {
                    invalidError.setVisible(true);
                }

            } catch (SQLException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_jButton_loginActionPerformed

    private void emptyErrorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emptyErrorMouseClicked
        emptyError.setVisible(false);
    }//GEN-LAST:event_emptyErrorMouseClicked

    private void invalidErrorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invalidErrorMouseClicked
        invalidError.setVisible(false);
    }//GEN-LAST:event_invalidErrorMouseClicked

    private void adminErrorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminErrorMouseClicked
        adminError.setVisible(false);
    }//GEN-LAST:event_adminErrorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    
                    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminError;
    private javax.swing.JLabel emptyError;
    private javax.swing.JLabel invalidError;
    private javax.swing.JButton jButton_login;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox_ut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_image;
    private javax.swing.JPanel jPanel_background;
    private javax.swing.JPanel jPanel_image;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
